# Generated by Django 3.2.3 on 2021-06-04 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=140)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('twitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
