# Generated by Django 3.2.1 on 2021-06-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='has_readed',
        ),
    ]
